### ISSUE TITLE
Code clean-up todo list

### ISSUE THREAD

**Issue by nandometzger** [jvargasmu/population_estimation#60]
- [ ] move list unrolling functions to utils
- [ ] move dataset building functions to another folder
- [ ] Remove parts of the script that are not a scale net
- [x] we don't need the "eval_only" functionality anymore
- [ ]
